// ═══════════════════════════════════════════════════════════════════════════════════
// den_sm120_driver_bridge.cpp — CUDA 12.8 Driver API Bridge Implementation
// ═══════════════════════════════════════════════════════════════════════════════════
//
// Compiled as C++ by the HOST compiler (g++/clang). Uses CUDA Driver API directly.
// Fatbin symbols are generated by the build system (xxd -i from .fatbin → .c).
//
// NOTE: Persistent kernel currently disabled by default (DEN_ROUTE=gemv is the
// default path). This bridge is a minimal stub — the GEMV path (Path A) is the
// proven working path. See den_dispatch.cuh for A/B selection logic.
//
// ═══════════════════════════════════════════════════════════════════════════════════

#include "den_sm120_driver_bridge.hpp"

#include <cstring>

// ─────────────────────────────────────────────────────────────────────────────────
// INIT — load fatbin, extract kernel function
// ─────────────────────────────────────────────────────────────────────────────────

bool DenSm120Driver::init() {
    if (m_initialized) return true;

    // Stub fatbin — not compiled, no persistent kernel available.
    if (den_mxf4nvf4_decode_sm120_fatbin_len == 0) {
        fprintf(stderr, "DEN_DRIVER: fatbin not compiled (len=0) — SM120 persistent kernel unavailable\n");
        return false;
    }

    // Load fatbin module via Driver API
    CUresult res = cuModuleLoadData(&m_module, den_mxf4nvf4_decode_sm120_fatbin);
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "DEN_DRIVER: cuModuleLoadData failed (%d) — falling back to GEMV\n", (int)res);
        return false;
    }

    // Extract kernel function
    res = cuModuleGetFunction(&m_kernel, m_module, "den_mxf4nvf4_decode_sm120_kernel");
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "DEN_DRIVER: cuModuleGetFunction failed (%d) — falling back to GEMV\n", (int)res);
        cuModuleUnload(m_module);
        m_module = nullptr;
        return false;
    }

    m_initialized = true;
    fprintf(stderr, "DEN_DRIVER: SM120 persistent kernel loaded and ready\n");
    return true;
}

// ─────────────────────────────────────────────────────────────────────────────────
// LAUNCH — launch persistent decode kernel via Driver API
// ─────────────────────────────────────────────────────────────────────────────────

bool DenSm120Driver::launch_gemv(
    const uint8_t* weights, const float* act, float* dst,
    int N, int K, CUstream stream,
    const float* tile_norms, int n_norms)
{
    if (!m_initialized) {
        fprintf(stderr, "DEN_DRIVER: launch_gemv called but not initialized\n");
        return false;
    }

    m_cu_stream = stream;

    // Kernel launch parameters: weights, act, dst, N, K, tile_norms, n_norms
    void* args[7] = {
        &weights, &act, &dst,
        &N, &K,
        &tile_norms, &n_norms
    };

    // Launch 1 CTA (persistent kernel manages its own grid internally)
    CUresult res = cuLaunchKernel(
        m_kernel,
        1, 1, 1,  // grid dim (persistent CTA uses single CTA)
        128, 1, 1, // block dim
        0,         // shared mem bytes
        m_cu_stream,
        args, nullptr);

    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "DEN_DRIVER: cuLaunchKernel failed (%d)\n", (int)res);
        return false;
    }
    return true;
}

// ─────────────────────────────────────────────────────────────────────────────────
// CLEANUP — unload module, reset state
// ─────────────────────────────────────────────────────────────────────────────────

void DenSm120Driver::cleanup() {
    if (m_module) {
        cuModuleUnload(m_module);
        m_module = nullptr;
    }
    m_kernel = nullptr;
    m_initialized = false;
}
