#pragma once
// ═══════════════════════════════════════════════════════════════════════════════════
// den_sm120_driver_bridge.hpp — CUDA 12.8 Driver API Bridge for SM120 Persistent CTA
// ═══════════════════════════════════════════════════════════════════════════════════
//
// Provides DenSm120Driver singleton that:
// - Loads the AOT fatbin compiled by CUDA 12.8 nvcc (den_mxf4nvf4_decode_sm120.fatbin)
// - Exposes launch_gemv() for the persistent CTA decode kernel
// - Falls back gracefully when fatbin is unavailable (len==0)
//
// The driver bridge is compiled as C++ by the HOST compiler (not nvcc).
// It uses the CUDA Driver API (not Runtime API) to load the fatbin module.
//
// ═══════════════════════════════════════════════════════════════════════════════════

#include <cuda.h>
#include <cstdint>
#include <cstdio>

// ─────────────────────────────────────────────────────────────────────────────────
// Fatbin symbols — embedded C array generated by xxd -i during build
// ─────────────────────────────────────────────────────────────────────────────────

extern "C" unsigned char den_mxf4nvf4_decode_sm120_fatbin[];
extern "C" unsigned int  den_mxf4nvf4_decode_sm120_fatbin_len;


// ─────────────────────────────────────────────────────────────────────────────────
// DenSm120Driver — singleton, wraps CUDA Driver API for persistent decode kernel
// ─────────────────────────────────────────────────────────────────────────────────

class DenSm120Driver {
public:
    static DenSm120Driver& instance() {
        static DenSm120Driver inst;
        return inst;
    }

    /// Returns true if the fatbin was loaded and kernel functions are available.
    bool is_initialized() const { return m_initialized; }

    /// Lazy init: loads fatbin via cuModuleLoadData, extracts kernel functions.
    /// Safe to call multiple times — only initializes once.
    bool init();

    /// Launch persistent GEMV decode kernel (Path B).
    /// Must only be called if is_initialized() returns true.
    /// Uses CUstream (CUDA Driver API) — cudaStream_t not visible to host compiler.
    /// Returns true if launch succeeded.
    bool launch_gemv(const uint8_t* weights, const float* act, float* dst,
                     int N, int K, CUstream stream,
                     const float* tile_norms, int n_norms);

    /// Unload fatbin module, reset state.
    void cleanup();

private:
    DenSm120Driver() : m_initialized(false), m_module(nullptr),
                       m_kernel(nullptr), m_cu_stream(nullptr) {}

    ~DenSm120Driver() { cleanup(); }

    // Non-copyable, non-movable
    DenSm120Driver(const DenSm120Driver&) = delete;
    DenSm120Driver& operator=(const DenSm120Driver&) = delete;

    bool     m_initialized;
    CUmodule m_module;
    CUfunction m_kernel;
    CUstream m_cu_stream;
};
